name: back_end_cuidapet
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.3.0
  dotenv: ^4.1.0
  get_it: ^7.6.0
  injectable: ^2.1.1
  jaguar_jwt: ^3.0.0
  logger: ^1.3.0
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  injectable_generator: ^2.1.5
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.4
  shelf_router_generator: ^1.0.6
